version: '3'

networks:
  app:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: courses_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - app

  php-8.1:
    container_name: courses_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.1'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
        user: sammy
        uid: 1000
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./php-ini/8.1/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_8_1_PORT}:9000"
    networks:
      - app

  mysql-8:
    image: mysql:8.0.21
    container_name: courses_mysql-8
    restart: always
    volumes:
      - ./mysql-8/data:/var/lib/mysql
      - ./mysql-8/conf.d:/etc/mysql/conf.d
      - ./mysql-8/logs:/var/log/mysql/
      - ./mysql-8/dump:/dump
    ports:
      - "${MYSQL_8_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - app

  phpmyadmin:
    depends_on:
      - mysql-8
    image: phpmyadmin/phpmyadmin
    container_name: courses_pma
    restart: always
    environment:
      PMA_HOST: mysql-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    networks:
      - app

  frontend:
    container_name: courses_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
      - "${FRONTEND_PORT}:3003"
    tty: true
    networks:
      - app


